/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdd.practice;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        FizzBuzzGame fizzBuzzGame = new FizzBuzzGame();
        for( int i = 1; i <= 1024; i++) {
            String result = fizzBuzzGame.say(i);
            System.out.println(i + " " + result);
        }
    }
}
