/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tdd.practice;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        for( int i = 0; i < 1024; i++) {
            FizzBuzzGame fizzBuzzGame = new FizzBuzzGame(i+1);
            String result = fizzBuzzGame.parse();
            System.out.println(i + 1 +" "+result);
        }
    }
}
